language: node_js
node_js: 10.15
cache:
  yarn: true
  directories:
  - "~/.cache"
install:
- yarn install --frozen-lockfile
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn test
notifications:
  email: false
deploy:
  api_key:
    secure: F+8RfAoZDAeYfAZRbsUyAax2UVRY/eNmiMj8ITdjx3meDMg6/JphzyAsJk17Bccs79rbJOmKKqwWPOd0BhJ/rwyaE0Jzy+woqHNkpOsmJE5CtikIe7qhPrVvysArb8mGhxvlAYleFKnAJ7ycX3K19p0ul5LcE/PzTL0xftvVgAwuyT59PEWOMKeLWMb9Ai1LqiebP8MZSQmIeb/0W4alB1O5MaIojwq7Bj3ZjZqyNJ1Y9LcodYZ9MtZyu+n3A1o+3fgzo6FQurYs3gf4XCRFVo4kSm4UcYqdVNy1wLGW3M1BWn7jCklWSY+USe6OJmsuxnLw6M0w8VtvcjQzOhaZu85yeaochEt9L3if2ZhFdmXAeSBqa39C9UiMdJ1V3cyDYKKBvQ0KqY9pDnGBB63f2Gab6SPN/buf1FcQcWSOYDCX2LT3vFbfPD7rpq7Szt2MK5xwKcztpdTQrB3gmusnbEdJaLPXTnYhKSrJm9niaVs1M7zB5EMpINzeeq7BSVaQZATqx6ZPSEiwsPE4pdHPswDndjm2z+pAlB95EjhQprecvmtwdTM8mg6PmhrQZQbbNuXhuaznCi+Zq9UxfoENHX40oIypflbfWT47A2BZivqF8f02gqMx64AdlOKjC3NACNAgacgklstDiFZKvjMOvExmlEdPPt9qvqAOfugndxY=
